// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE


function playSound(e) {
  console.log(e);
  return /* () */0;
}

function keys(param) {
  return param.querySelectorAll(".key");
}

export {
  playSound ,
  keys ,
  
}
/* No side effect */
